--- CREADO POR César Burgos



-- ======================
-- CREANDO USUARIO PARA EL PROYECTO

CREATE USER ulapets IDENTIFIED BY ulapetspass
    DEFAULT TABLESPACE users
    TEMPORARY TABLESPACE temp
    QUOTA UNLIMITED ON users;

-- Dar privilegios básicos para conectarse y trabajar con sus tablas
GRANT CREATE SESSION TO ulapets;  -- Permiso para hacer login
GRANT CREATE TABLE TO ulapets; --Permiso para crear tablas
GRANT CREATE SEQUENCE TO ulapets; -- Permiso para crear secuencias
GRANT CREATE VIEW TO ulapets; -- Permiso para crear vistas
GRANT CREATE TRIGGER TO ulapets;  -- Permiso para crear triggers
GRANT CREATE PROCEDURE TO ulapets; -- Permiso para crear funciones y procedimientos almacenados
GRANT CREATE MATERIALIZED VIEW TO ulapets; -- Permiso para crear vistas materializadas
GRANT CREATE DATABASE LINK TO ulapets; -- Permiso para crear database link

-- Rol resource
GRANT RESOURCE TO ulapets;





-- ====================== TABLA ADOPTANTE
--- Previniendo creación de tabla (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE ADOPTANTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE !=-942 THEN
        RAISE;
    END IF;
END;

---- SELECCIONANDO USUARIO PARA LA BD
ALTER SESSION SET CURRENT_SCHEMA = ulapets;

CREATE TABLE ADOPTANTE(
    ID_ADOPTANTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO VARCHAR2(100),
    TELEFONO VARCHAR2(10),
    CORREO VARCHAR2(100),
    FECHA_REGISTRO DATE,
    ESTADO NUMBER(2) DEFAULT 1 NOT NULL,

    CONSTRAINT PK_ID_ADOPTANTE_ADOPTANTE PRIMARY KEY (ID_ADOPTANTE),
    CONSTRAINT CHK_ESTADO_ADOPTANTE CHECK (ESTADO IN (0, 99))
);

COMMENT ON TABLE ADOPTANTE IS 'Tabla de adoptantes';
COMMENT ON COLUMN ADOPTANTE.ID_ADOPTANTE IS 'ID de Adoptante';
COMMENT ON COLUMN ADOPTANTE.NOMBRE IS 'Nombre(s) del adoptante';
COMMENT ON COLUMN ADOPTANTE.APELLIDO_PATERNO IS 'Apellido Paterno del adoptante';
COMMENT ON COLUMN ADOPTANTE.APELLIDO_MATERNO IS 'Apellido Materno del adoptante';
COMMENT ON COLUMN ADOPTANTE.TELEFONO IS 'Telefono del adoptante';
COMMENT ON COLUMN ADOPTANTE.CORREO IS 'Correo electrónico del adoptante';
COMMENT ON COLUMN ADOPTANTE.FECHA_REGISTRO IS 'Fecha de registro del adoptante';
COMMENT ON COLUMN ADOPTANTE.ESTADO IS 'Estado activo Adoptante 1-Activo/0-Inactivo';

COMMIT;

-- Creando secuencia de ID en adoptantes (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_ADOPTANTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE SEQUENCE SEQ_ADOPTANTE START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE;





-- ====================== TABLA DOMICILIO_ADOPTANTE
--- Previniendo creación de tabla (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DOMICILIO_ADOPTANTE CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

---- SELECCIONANDO USUARIO PARA LA BD
ALTER SESSION SET CURRENT_SCHEMA = ulapets;

CREATE TABLE DOMICILIO_ADOPTANTE(
    ID_DOMICILIO NUMBER NOT NULL,
    ID_ADOPTANTE NUMBER NOT NULL,
    CALLE VARCHAR2(100),
    NUMERO_EXTERIOR VARCHAR2(4),
    COLONIA VARCHAR2(200),
    CIUDAD VARCHAR2(200),
    ESTADO_GEOGRAFICO VARCHAR2(200),
    CODIGO_POSTAL NUMBER(5),
    ESTADO NUMBER(2) DEFAULT 1 NOT NULL,

    CONSTRAINT PK_ID_DOMICILIO_DOMICILIO_ADOPTANTE PRIMARY KEY (ID_DOMICILIO),
    CONSTRAINT CHK_ESTADO_DOMICILIO_ADOPTANTE CHECK (ESTADO IN (0,99))
);

COMMENT ON TABLE DOMICILIO_ADOPTANTE IS 'Tabla de Domicilio de Adoptantes';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.ID_DOMICILIO IS 'ID del domicilio del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.ID_ADOPTANTE IS 'ID del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.CALLE IS 'Calle del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.NUMERO_EXTERIOR IS 'Numero exterior del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.COLONIA IS 'Colonia del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.CIUDAD IS 'Ciudad del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.ESTADO_GEOGRAFICO IS 'Estado del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.CODIGO_POSTAL IS 'Codigo postal del adoptante';
COMMENT ON COLUMN DOMICILIO_ADOPTANTE.ESTADO IS 'Estado activo Adoptante 1-Activo/0-Inactivo';

COMMIT;

-- Creando secuencia de ID en domicilio adoptantes (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DOM_ADOPTANTE';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE SEQUENCE SEQ_DOM_ADOPTANTE START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE;





-- ====================== TABLA MASCOTA
--- Previniendo creación de tabla (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE MASCOTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

---- SELECCIONANDO USUARIO PARA LA BD
ALTER SESSION SET CURRENT_SCHEMA = ulapets;

CREATE TABLE MASCOTA(
    ID_MASCOTA NUMBER NOT NULL,
    ID_ADOPTANTE NUMBER NOT NULL,
    NOMBRE VARCHAR2(100),
    ESPECIE VARCHAR2(100),
    RAZA VARCHAR2(100),
    SEXO VARCHAR2(1) NOT NULL,
    FECHA_NACIMIENTO DATE,
    PESO DECIMAL,
    COLOR VARCHAR2(100),
    ESTADO NUMBER(2) DEFAULT 1 NOT NULL,

    CONSTRAINT PK_ID_MASCOTA_MASCOTA PRIMARY KEY(ID_MASCOTA),
    CONSTRAINT CHK_ESTADO_MASCOTA CHECK (ESTADO IN (0,99))
);

COMMENT ON TABLE MASCOTA IS 'Tabla de Mascotas';
COMMENT ON COLUMN MASCOTA.ID_MASCOTA IS 'ID de la mascota';
COMMENT ON COLUMN MASCOTA.ID_ADOPTANTE IS 'ID del adoptante';
COMMENT ON COLUMN MASCOTA.NOMBRE IS 'Nombre de la mascota';
COMMENT ON COLUMN MASCOTA.ESPECIE IS 'Especie de la mascota';
COMMENT ON COLUMN MASCOTA.RAZA IS 'Raza de la mascota';
COMMENT ON COLUMN MASCOTA.SEXO IS 'Sexo de la mascota M-Macho/H-Hembra';
COMMENT ON COLUMN MASCOTA.FECHA_NACIMIENTO IS 'fecha de nacimiento de mascota';
COMMENT ON COLUMN MASCOTA.PESO IS 'Peso de la mascota';
COMMENT ON COLUMN MASCOTA.COLOR IS 'Color de la mascota';
COMMENT ON COLUMN MASCOTA.ESTADO  IS 'Estado activo Adoptante 1-Activo/0-Inactivo';

COMMIT;

-- Creando secuencia de ID en mascotas (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_MASCOTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE SEQUENCE SEQ_MASCOTA START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE;





-- ====================== TABLA DISPOSITIVO_MASCOTA
--- Previniendo creación de tabla (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE DISPOSITIVO_MASCOTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

---- SELECCIONANDO USUARIO PARA LA BD
ALTER SESSION SET CURRENT_SCHEMA = ulapets;

CREATE TABLE DISPOSITIVO_MASCOTA(
    ID_DISPOSITIVO NUMBER NOT NULL,
    ID_MASCOTA NUMBER NOT NULL,
    NUM_CHIP VARCHAR2(100),
    TIPO_DISPOSITIVO VARCHAR2(100),
    FECHA_INSTALACION DATE,
    ESTADO NUMBER(2),

    CONSTRAINT PK_ID_DISPOSITIVO_DISPOSITIVO_MASCOTA PRIMARY KEY(ID_DISPOSITIVO),
    CONSTRAINT CHK_ESTADO_DISPOSITIVO_MASCOTA CHECK (ESTADO IN (0,99))
);

COMMENT ON TABLE DISPOSITIVO_MASCOTA IS 'Tabla de Dispositivos de Mascotas';
COMMENT ON COLUMN DISPOSITIVO_MASCOTA.ID_DISPOSITIVO IS 'ID dispositivo';
COMMENT ON COLUMN DISPOSITIVO_MASCOTA.ID_MASCOTA IS 'ID mascota';
COMMENT ON COLUMN DISPOSITIVO_MASCOTA.NUM_CHIP IS 'Numerio serie de chip';
COMMENT ON COLUMN DISPOSITIVO_MASCOTA.TIPO_DISPOSITIVO IS 'Tipo de dispositivo';
COMMENT ON COLUMN DISPOSITIVO_MASCOTA.FECHA_INSTALACION IS 'Fecha instalación dispositivo';
COMMENT ON COLUMN DISPOSITIVO_MASCOTA.ESTADO  IS 'Estado activo Adoptante 1-Activo/0-Inactivo';

COMMIT;

-- Creando secuencia de ID en Dispositivo mascotas (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_DISP_MASCOTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE SEQUENCE SEQ_DISP_MASCOTA START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE;





-- ====================== TABLA VACUNA_MASCOTA
--- Previniendo creación de tabla (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE VACUNA_MASCOTA CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
        RAISE;
    END IF;
END;

---- SELECCIONANDO USUARIO PARA LA BD
ALTER SESSION SET CURRENT_SCHEMA = ulapets;

CREATE TABLE VACUNA_MASCOTA(
    ID_VACUNA NUMBER NOT NULL,
    ID_MASCOTA NUMBER NOT NULL,
    NOMBRE_VACUNA VARCHAR2(100),
    FECHA_APLICACION DATE,
    FECHA_PROXIMA_DOSIS DATE,
    VETERINARIO_RESPONSABLE VARCHAR2(200),
    ESTADO NUMBER(2) DEFAULT 1,

    CONSTRAINT PK_ID_VACUNA_VACUNA_MASCOTA PRIMARY KEY (ID_VACUNA),
    CONSTRAINT CHK_ESTADO_VACUNA_MASCOTA CHECK (ESTADO IN (0,99))
);

COMMENT ON TABLE VACUNA_MASCOTA IS 'Tabla de historico Vacuna de Mascotas';
COMMENT ON COLUMN VACUNA_MASCOTA.ID_VACUNA IS 'ID vacuna';
COMMENT ON COLUMN VACUNA_MASCOTA.ID_MASCOTA IS 'ID mascota';
COMMENT ON COLUMN VACUNA_MASCOTA.NOMBRE_VACUNA IS 'Vacuna aplicada';
COMMENT ON COLUMN VACUNA_MASCOTA.FECHA_APLICACION IS 'Fecha de aplicación';
COMMENT ON COLUMN VACUNA_MASCOTA.FECHA_PROXIMA_DOSIS IS 'Fecha proxima dosis';
COMMENT ON COLUMN VACUNA_MASCOTA.VETERINARIO_RESPONSABLE IS 'Nombre de veterinario responsable';
COMMENT ON COLUMN VACUNA_MASCOTA.ESTADO  IS 'Estado activo Adoptante 1-Activo/0-Inactivo';

COMMIT;

-- Creando secuencia de ID en vacuna mascotas (EJECUTANDO PLSQL)
BEGIN
    EXECUTE IMMEDIATE 'DROP SEQUENCE SEQ_VACUNA_MASCOTA';
EXCEPTION WHEN OTHERS THEN NULL;
END;

CREATE SEQUENCE SEQ_VACUNA_MASCOTA START WITH 1 INCREMENT BY 1 MINVALUE 1 NOCACHE;
